<?php /** @var $this Mage_Customer_Block_Form_Register */ ;?>
<?php if(Mage::helper('sh_telesign')->isEnableAddressOnRegisterPage()): ?>
    <li class="hidden">
        <input type="hidden" name="create_address" value="1" />
    </li>
    <li class="fields">
        <div class="field">
            <label for="company"><?php echo $this->__('Company') ?></label>
            <div class="input-box">
                <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
            </div>
        </div>
        <div class="field">
            <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
            <div class="input-box">
                <input type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
            </div>
        </div>
    </li>
    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
    <li class="wide">
        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
        <div class="input-box">
            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
        </div>
    </li>
    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
        <li class="wide">
            <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
            <div class="input-box">
                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
            </div>
        </li>
    <?php endfor; ?>
    <li class="fields">
        <div class="field">
            <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
            <div class="input-box">
                <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
            </div>
        </div>
        <div class="field">
            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
            <div class="input-box">
                <select id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                    //<![CDATA[
                    $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                    //]]>
                </script>
                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
            </div>
        </div>
    </li>
    <li class="fields">
        <div class="field">
            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
            <div class="input-box">
                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
            </div>
        </div>
        <div class="field">
            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
            <div class="input-box">
                <?php echo $this->getCountryHtmlSelect() ?>
            </div>
        </div>
    </li>
    <li class="hidden">
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1" />
    </li>
<?php endif; ?>
