<li class="fields">
    <div class="field">
        <label for="telesign_telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
        <div class="input-box">
            <input type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
        </div>
    </div>
</li>