<?php
$notificationTypes = new SH_Telesign_Model_System_Config_Source_Type_Notification();
?>
<li class="fields">
    <div class="field">
        <label for="telesign_type" class="required"><em>*</em><?php echo $this->__('Notification Type') ?></label>
        <div class="input-box">
            <select id="telesign_type" name="telesign_type" title="<?php echo $this->quoteEscape($this->__('Notification Type')) ?>" class="validate-select">
                <?php foreach($notificationTypes->getCurrentNotificationType() as $key => $type): ?>
                    <option value="<?php echo $key;?>"><?php echo $type?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</li>
