<?php /* @var $this SH_Telesign_Block_Verify */ ?>
<li>
    <div class="field">
        <div class="input-box">
            <input type="radio" name="verify_code_already_send" value="0" checked="checked"/><?php echo $this->__('Enter the correct telephone verification code') ?><br/>
            <input type="radio" name="verify_code_already_send" value="1"/><?php echo $this->__('I already enter the correct telephone verification code') ?>
        </div>
        <div class="input-box" id="verify_code_telephone_div">
            <label for="verify_code" class="required"><em>*</em><?php echo $this->__('Telephone Code') ?></label>

            <div class="input-box">
                <input type="text" name="verify_code" id="verify_code" title="<?php echo $this->__('Code') ?>"
                       class="input-text required-entry"/>
            </div>
        </div>
    </div>
</li>
<li>
    <a href="<?php echo $this->getUrl('sh_telesign/verify/resendForm'); ?>"
       class="f-left"><?php echo $this->__('Resend Telephone Verification Code') ?></a>
</li>
<script type="text/javascript">
    enterVerificationCode('verify_code_already_send', jQuery('#verify_code'), jQuery('#verify_code_telephone_div'));
</script>
